<template>
  <el-card class="" id="cloudCard" :body-style="{padding:0}" shadow="never">
    <template #header>
      <el-row class="chartHeader" align="middle" :gutter="10">
        <el-col :span="1">词云图</el-col>
        <el-col :span="8">
          <el-input v-model="maskSrc" />
        </el-col>
        <el-col :span="1">
          <el-button type="primary" @click="changeMask">更新</el-button>
        </el-col>
      </el-row>
    </template>
    <div id="cloudChart" class="chartBody"></div>
  </el-card>
</template>
<script lang="ts" setup>
import { inject, onMounted, ref } from 'vue';
import { apiGet } from '@/api';
import { useRoute } from 'vue-router';

const route = useRoute();
const echarts: any = inject('echarts');
const maskSrc = ref('/images/mask/c7799383fa1c43f98c2efda87eaebf0a.png');
const words = [
  { name: '专业', value: 576 },
  { name: '幼儿园', value: 523 },
  { name: '20220', value: 522 },
  { name: '学前教育', value: 465 },
  { name: '考生', value: 438 },
  { name: '专科', value: 392 },
  { name: '01', value: 321 },
  { name: '学院', value: 314 },
  { name: '02', value: 283 },
  { name: '招生', value: 281 },
  { name: '07', value: 260 },
  { name: '学校', value: 242 },
  { name: '大学', value: 237 },
  { name: '科技大学', value: 235 },
  { name: '杭州电子', value: 233 },
  { name: '2021', value: 213 },
  { name: '复试', value: 188 },
  { name: '公司', value: 185 },
  { name: '2022年', value: 175 },
  { name: '录取', value: 173 },
  { name: '高校', value: 164 },
  { name: '电子科技', value: 152 },
  { name: '资料', value: 141 },
  { name: '精品', value: 137 },
  { name: '浙江省', value: 134 },
  { name: '学生', value: 132 },
  { name: '2022', value: 131 },
  { name: '2020', value: 124 },
  { name: '06', value: 120 },
  { name: 'pdf', value: 119 },
  { name: '本科', value: 119 },
  { name: '杭电', value: 110 },
  { name: '成绩', value: 108 },
  { name: '电源', value: 104 },
  { name: '我校', value: 101 },
  { name: '2023年', value: 99 },
  { name: '杭州', value: 97 },
  { name: '微生物', value: 96 },
  { name: '硕士研究生', value: 94 },
  { name: '填报', value: 92 },
  { name: '食品', value: 91 },
  { name: '工作', value: 91 },
  { name: '发展', value: 89 },
  { name: '宁波大学', value: 88 },
  { name: '考研', value: 87 },
  { name: '03', value: 86 },
  { name: '国家', value: 83 },
  { name: '信息', value: 82 },
  { name: '技术学院', value: 81 },
  { name: '街道', value: 79 },
  { name: '领域', value: 77 },
  { name: '专科学校', value: 77 },
  { name: '高等', value: 73 },
  { name: '报告', value: 71 },
  { name: '提升', value: 71 },
  { name: '职业', value: 71 },
  { name: 'CE', value: 70 },
  { name: '全国', value: 69 },
  { name: '研究生', value: 67 },
  { name: '报考', value: 66 },
  { name: '调剂', value: 65 },
  { name: '毕业生', value: 64 },
  { name: '亿元', value: 64 },
  { name: '学科', value: 64 },
  { name: '2000', value: 62 },
  { name: '1999', value: 61 },
  { name: '计算机', value: 61 },
  { name: '2001', value: 60 },
  { name: '艺术', value: 60 },
  { name: '建设', value: 59 },
  { name: '当事人', value: 58 },
  { name: '研究', value: 57 },
  { name: '综合', value: 56 },
  { name: '电子书', value: 56 },
  { name: '技术', value: 56 },
  { name: '考研复试', value: 56 },
  { name: '张充和', value: 55 },
  { name: '建议', value: 54 },
  { name: '联席', value: 54 },
  { name: '申请', value: 54 },
  { name: '人才', value: 52 },
  { name: '情况', value: 52 },
  { name: '食品安全', value: 52 },
  { name: '2207', value: 52 },
  { name: '产品', value: 51 },
  { name: '市场', value: 50 },
  { name: '培养', value: 49 },
  { name: '科学与技术', value: 49 },
  { name: '希望', value: 49 },
  { name: '一段', value: 48 },
  { name: '转专业', value: 47 },
  { name: '西安电子科技大学', value: 46 },
  { name: '工程学院', value: 46 },
  { name: '访谈', value: 45 },
  { name: '院校', value: 45 },
  { name: '占比', value: 43 },
  { name: '同学', value: 43 },
  { name: '挖矿', value: 43 },
  { name: '项目', value: 42 },
  { name: '选择', value: 42 },
  { name: '招办', value: 42 },
  { name: '浙江', value: 42 },
  { name: '西湖大学', value: 41 },
  { name: '通信', value: 41 },
  { name: '14', value: 40 },
  { name: '2019', value: 40 },
  { name: '石楠花', value: 39 },
  { name: '检验', value: 38 },
  { name: '需求', value: 38 },
  { name: '预增', value: 36 },
  { name: '都是', value: 36 },
  { name: '刘子豪', value: 35 },
  { name: '录取通知书', value: 35 },
  { name: '课程', value: 34 },
  { name: '公路', value: 34 },
  { name: '营收', value: 34 },
  { name: '纤维艺术', value: 34 },
  { name: '老师', value: 33 },
  { name: '两人', value: 33 },
  { name: '华为', value: 33 },
  { name: '介绍', value: 33 },
  { name: '教学', value: 32 },
  { name: '活动', value: 32 },
  { name: '丽江', value: 32 },
  { name: '刘丹', value: 32 },
  { name: '网上报名', value: 32 },
  { name: '位次', value: 31 },
  { name: '学习', value: 31 },
  { name: '志愿', value: 31 },
  { name: '监督管理局', value: 31 },
  { name: '5G', value: 31 },
  { name: '2017', value: 30 },
  { name: '生活', value: 30 },
  { name: '确认', value: 30 },
  { name: '计划', value: 29 },
  { name: 'com', value: 29 },
  { name: '委员会', value: 29 },
  { name: '物理', value: 29 },
  { name: '我国', value: 28 },
  { name: '校友', value: 28 },
  { name: '报名', value: 28 },
  { name: '检测', value: 28 },
  { name: '面试', value: 28 },
  { name: '省份', value: 28 },
  { name: '数据', value: 28 },
  { name: '创新', value: 27 },
  { name: '独立学院', value: 27 },
  { name: '依法', value: 27 },
  { name: '相关', value: 26 },
  { name: '的人', value: 26 },
  { name: '分析', value: 26 },
  { name: '杭州市', value: 26 },
  { name: '平台', value: 26 },
  { name: '爬树', value: 26 },
  { name: '企业', value: 26 },
  { name: '录取分数线', value: 26 },
  { name: '加试', value: 26 },
  { name: '上半年', value: 25 },
  { name: 'aa', value: 25 },
  { name: 'SA', value: 25 },
  { name: '中国', value: 25 },
  { name: '左立', value: 24 },
  { name: 'GB', value: 24 },
  { name: '产业', value: 24 },
  { name: '操应旺', value: 24 },
  { name: '特种电源', value: 24 },
  { name: '时间', value: 23 },
  { name: '美国', value: 23 },
  { name: '2018年', value: 23 },
  { name: '2021年', value: 23 },
  { name: '规划', value: 23 },
  { name: '电子', value: 23 },
  { name: '云和', value: 23 },
  { name: '主持人', value: 22 },
  { name: '作出', value: 22 },
  { name: '系统', value: 22 },
  { name: '发现', value: 22 },
  { name: '法学', value: 22 },
  { name: '标准', value: 22 },
  { name: '拜登', value: 22 },
  { name: '汇总', value: 22 },
  { name: '考研院校', value: 22 },
  { name: '科目', value: 22 },
  { name: '梯队', value: 22 },
  { name: '特种', value: 22 },
  { name: '提前批', value: 21 },
  { name: '全球', value: 21 },
  { name: '净利', value: 21 },
  { name: '金晶', value: 21 },
  { name: '进口', value: 21 },
  { name: '孟礼强', value: 21 },
  { name: '北京', value: 21 },
  { name: '大数据', value: 21 },
  { name: '贷款', value: 21 },
  { name: '小坚', value: 21 },
  { name: '行政处罚', value: 21 },
  { name: '智能', value: 21 },
  { name: '友发', value: 20 },
  { name: '校友会', value: 20 },
  { name: '微生物学', value: 20 },
  { name: '投档', value: 20 },
  { name: '杭州银行', value: 20 },
  { name: 'PC', value: 20 },
  { name: '教育部', value: 20 },
  { name: '特色', value: 20 },
  { name: '省级', value: 20 },
  { name: '省内', value: 20 },
  { name: '深造', value: 19 },
  { name: '数字经济', value: 19 },
  { name: '警方', value: 19 },
  { name: '竞赛', value: 19 },
  { name: '模式', value: 19 },
  { name: '母校', value: 19 },
  { name: '产业学院', value: 19 },
  { name: '初试', value: 19 },
  { name: '国家标准', value: 19 },
  { name: '代表', value: 19 },
  { name: '电子信息', value: 19 },
  { name: '网上', value: 19 },
  { name: '伊朗', value: 19 },
  { name: '招生计划', value: 19 },
  { name: '浙江大学', value: 18 },
  { name: '中外合作', value: 18 },
  { name: '自动化', value: 18 },
  { name: '优势', value: 18 },
  { name: '国际', value: 18 },
  { name: '成都', value: 18 },
  { name: '参与', value: 18 },
  { name: '2017年', value: 18 },
  { name: '冷链', value: 18 },
  { name: '基础', value: 18 },
  { name: '数字化', value: 18 },
  { name: '南京大学', value: 18 },
  { name: '热射病', value: 17 },
  { name: '溯源', value: 17 },
  { name: '就业', value: 17 },
  { name: '跨境电商', value: 17 },
  { name: '211', value: 17 },
  { name: '查验', value: 17 },
  { name: '初试成绩', value: 17 },
  { name: '广州', value: 17 },
  { name: '贵安', value: 17 },
  { name: '杭师', value: 17 },
  { name: '选考', value: 17 },
  { name: '政策', value: 17 },
  { name: '执行', value: 17 },
  { name: '招生考试', value: 17 },
  { name: '志愿填报', value: 16 },
  { name: '咨询电话', value: 16 },
  { name: '校区', value: 16 },
  { name: '一所', value: 16 },
  { name: '网络空间', value: 16 },
  { name: '投档线', value: 16 },
  { name: '纤维', value: 16 },
  { name: '更多', value: 16 },
  { name: '大陆', value: 16 },
  { name: '2019年', value: 16 },
  { name: '985', value: 16 },
  { name: '深度', value: 16 },
  { name: '石楠', value: 16 },
  { name: '四川大学', value: 15 },
  { name: '台北', value: 15 },
  { name: '人员', value: 15 },
  { name: '设计', value: 15 },
  { name: '兰亭', value: 15 },
  { name: '名称', value: 15 },
  { name: '经营', value: 15 },
  { name: '会场', value: 15 },
  { name: 'http', value: 15 },
  { name: '本科生', value: 15 },
  { name: '鄙视链', value: 15 },
  { name: '西湖', value: 15 },
  { name: '行业', value: 15 },
  { name: '学历', value: 15 },
  { name: '凶手', value: 14 },
  { name: '应届', value: 14 },
  { name: '消费', value: 14 },
  { name: '位居', value: 14 },
  { name: '白梅', value: 14 },
  { name: '打造', value: 14 },
  { name: '2020年', value: 14 },
  { name: '的是', value: 14 },
  { name: '单位', value: 14 },
  { name: '分享', value: 14 },
  { name: '高层次人才', value: 14 },
  { name: '感谢', value: 14 },
  { name: '管理', value: 14 },
  { name: '基地', value: 14 },
  { name: '换电', value: 14 },
  { name: '科学', value: 14 },
  { name: '科技', value: 14 },
  { name: '入校', value: 14 },
  { name: '入学', value: 14 },
  { name: '瑞士', value: 14 },
  { name: '平行志愿', value: 14 },
  { name: '起夜', value: 14 },
  { name: '气味', value: 14 },
  { name: '通知书', value: 14 },
  { name: '实训', value: 14 },
  { name: '市集', value: 13 },
  { name: '事情', value: 13 },
  { name: '同比', value: 13 },
  { name: '台湾', value: 13 },
  { name: '青海', value: 13 },
  { name: '全日制', value: 13 },
  { name: '区块链', value: 13 },
  { name: '朋友', value: 13 },
  { name: '三诊', value: 13 },
  { name: '进口水果', value: 13 },
  { name: '教授', value: 13 },
  { name: '罗某', value: 13 },
  { name: '类型', value: 13 },
  { name: '科研', value: 13 },
  { name: '国内', value: 13 },
  { name: '贵州', value: 13 },
  { name: '桂林电子', value: 13 },
  { name: '合作', value: 13 },
  { name: '俄罗斯', value: 13 },
  { name: '导师', value: 13 },
  { name: '到了', value: 13 },
  { name: 'https', value: 13 },
  { name: '创作', value: 13 },
  { name: '成员', value: 13 },
  { name: '文化', value: 13 },
  { name: '违法行为', value: 13 },
  { name: '投资', value: 13 },
  { name: '我院', value: 13 },
  { name: '应聘', value: 13 },
  { name: '一位', value: 13 },
  { name: '新生', value: 13 },
  { name: '学生会', value: 13 },
  { name: '整改', value: 13 },
  { name: '中东', value: 13 },
  { name: '增长', value: 13 },
  { name: '重点', value: 12 },
  { name: '周岁', value: 12 },
  { name: '专业学位', value: 12 },
  { name: '专委会', value: 12 },
  { name: '最终', value: 12 },
  { name: '徐毅', value: 12 },
  { name: '消费券', value: 12 },
  { name: '投放', value: 12 },
  { name: '推动', value: 12 },
  { name: '万元', value: 12 },
  { name: '参考', value: 12 },
  { name: '卞之琳', value: 12 },
  { name: '案件', value: 12 },
  { name: '60', value: 12 },
  { name: '纺织服装', value: 12 },
  { name: '该行', value: 12 },
  { name: '负责', value: 12 },
  { name: '附件', value: 12 },
  { name: '复查', value: 12 },
  { name: '海康威视', value: 12 },
  { name: '工学院', value: 12 },
  { name: '控制线', value: 12 },
  { name: '纳西族', value: 12 },
  { name: '考核', value: 12 },
  { name: '患者', value: 12 },
  { name: '人工智能', value: 12 },
  { name: '沙特', value: 12 },
  { name: '朋友圈', value: 12 },
  { name: '平均分', value: 12 },
  { name: '妻子', value: 12 },
  { name: '宋韵', value: 12 },
  { name: '数据中心', value: 12 },
  { name: '深圳', value: 12 },
  { name: '深圳大学', value: 11 },
  { name: '世界', value: 11 },
  { name: '排名', value: 11 },
  { name: '培训中心', value: 11 },
  { name: '年龄', value: 11 },
  { name: '加分', value: 11 },
  { name: '检查', value: 11 },
  { name: '内容', value: 11 },
  { name: '路威', value: 11 },
  { name: '两所', value: 11 },
  { name: '联盟', value: 11 },
  { name: '高省', value: 11 },
  { name: '国家级', value: 11 },
  { name: '杭州亚运会', value: 11 },
  { name: '法学院', value: 11 },
  { name: '导致', value: 11 },
  { name: '待遇', value: 11 },
  { name: '调入', value: 11 },
  { name: '50', value: 11 },
  { name: '13', value: 11 },
  { name: '测试', value: 11 },
  { name: '报考点', value: 11 },
  { name: '城市', value: 11 },
  { name: '成功', value: 11 },
  { name: '统一', value: 11 },
  { name: '违反', value: 11 },
  { name: '学期', value: 11 },
  { name: '以色列', value: 11 },
  { name: '用户', value: 11 },
  { name: '主管部门', value: 11 },
  { name: '制品', value: 11 },
  { name: '卓越', value: 10 },
  { name: '资格', value: 10 },
  { name: '一种', value: 10 },
  { name: '疫情', value: 10 },
  { name: '研究生招生', value: 10 },
  { name: '学科评估', value: 10 },
  { name: '王兴', value: 10 },
  { name: '投档分', value: 10 },
  { name: '持续', value: 10 },
  { name: '22', value: 10 },
  { name: 'xing', value: 10 },
  { name: 'keji', value: 10 },
  { name: '红梅', value: 10 },
  { name: '郭旭东', value: 10 },
  { name: '海龟', value: 10 },
  { name: '改善', value: 10 },
  { name: '两名', value: 10 },
  { name: '领导', value: 10 },
  { name: '理科', value: 10 },
  { name: '科学家', value: 10 },
  { name: '论坛', value: 10 },
  { name: '盲盒', value: 10 },
  { name: '母亲', value: 10 },
  { name: '江苏', value: 10 },
  { name: '嘉宾', value: 10 },
  { name: '华芳', value: 10 },
  { name: '酒店', value: 10 },
  { name: '精英', value: 10 },
  { name: '南京审计', value: 10 },
  { name: '社会', value: 10 },
  { name: '身体', value: 10 },
  { name: '深大', value: 10 },
  { name: '实验班', value: 10 },
  { name: '实践', value: 9 },
  { name: '生源', value: 9 },
  { name: '书记', value: 9 },
  { name: '视觉传达', value: 9 },
  { name: '数字媒体', value: 9 },
  { name: '双一流', value: 9 },
  { name: '提供', value: 9 },
  { name: '人数', value: 9 },
  { name: '趋势', value: 9 },
  { name: '金审学院', value: 9 },
  { name: '教育考试院', value: 9 },
  { name: '木玩', value: 9 },
  { name: '龙头', value: 9 },
  { name: '快乐', value: 9 },
  { name: '利息收入', value: 9 },
  { name: '两位', value: 9 },
  { name: '高速公路', value: 9 },
  { name: '工作人员', value: 9 },
  { name: '公路网', value: 9 },
  { name: '供应链', value: 9 },
  { name: '互联网', value: 9 },
  { name: '当代', value: 9 },
  { name: '副总经理', value: 9 },
  { name: '服务', value: 9 },
  { name: '分数线', value: 9 },
  { name: 'm3', value: 9 },
  { name: 'oogle', value: 9 },
  { name: '超出', value: 9 },
  { name: '层次', value: 9 },
  { name: '大会', value: 9 },
  { name: '报道', value: 9 },
  { name: '膀胱', value: 9 },
  { name: '本周', value: 9 },
  { name: '统计', value: 9 },
  { name: '团队', value: 9 },
  { name: '推进', value: 9 },
  { name: '文旅', value: 9 },
  { name: '想要', value: 9 },
  { name: '现场', value: 9 },
  { name: '下降', value: 9 },
  { name: '央行', value: 9 },
  { name: '一流', value: 9 },
  { name: '疫情防控', value: 9 },
  { name: '智能制造', value: 9 },
  { name: '智慧公路', value: 9 },
  { name: '种植', value: 9 },
  { name: '中暑', value: 9 },
  { name: '这所', value: 9 },
  { name: '招聘', value: 8 },
  { name: '中所含', value: 8 },
  { name: '专业志愿', value: 8 },
  { name: '饮水量', value: 8 },
  { name: '一句', value: 8 },
  { name: '研究报告', value: 8 },
  { name: '腥臭味', value: 8 },
  { name: '校企合作', value: 8 },
  { name: '西财', value: 8 },
  { name: '味道', value: 8 },
  { name: '微观世界', value: 8 },
  { name: '标题', value: 8 },
  { name: '不含', value: 8 },
  { name: '表现', value: 8 },
  { name: '拨备覆盖率', value: 8 },
  { name: '博览会', value: 8 },
  { name: '补贴', value: 8 },
  { name: '催化剂', value: 8 },
  { name: '存款', value: 8 },
  { name: '产学研', value: 8 },
  { name: 'MBA', value: 8 }
];
let eleDom: any;
let chart: any;
let option = {
  series: [
    {
      type: 'wordCloud',
      shape: 'cirle',
      keepAspect: true,
      left: 'center',
      top: 'center',
      width: '100%',
      height: '100%',
      right: null,
      bottom: null,
      sizeRange: [12, 60],
      rotationRange: [-90, 90],
      rotationStep: 45,
      gridSize: 4,
      drawOutOfBound: false,
      layoutAnimation: true,
      textStyle: {
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        color: function () {
          return (
            'rgb(' +
            [
              Math.round(Math.random() * 160),
              Math.round(Math.random() * 160),
              Math.round(Math.random() * 160)
            ].join(',') +
            ')'
          );
        }
      },
      emphasis: {
        focus: 'self',
        textStyle: {
          textShadowBlur: 10,
          textShadowColor: '#333'
        }
      },
      data: words
    }
  ]
};

onMounted(() => {
  eleDom = document.getElementById('cloudChart');
  chart = echarts.init(eleDom);

  chart.setOption(option);
});
const changeMask = () => {
  let maskImage = new Image();
  maskImage.src = maskSrc.value;
  maskImage.onload = () => {
    option.series[0].maskImage = maskImage;
    chart.setOption(option);
    // const card = document.getElementById('cloudCard');
    // card?.requestFullscreen().then(() => {
    //   option.series[0].width = (window.innerWidth * 0.9).toString() + 'px';
    //   option.series[0].height = (window.innerHeight * 0.8).toString() + 'px';
      
      // console.log(option.series[0].width, option.series[0].height);
    // });
  };
};
</script>
<style scoped>
#cloudChart {
  width: 900px;
  height: 750px;
}
</style>
